# Config for GCP App Engine (free tier)
runtime: python311

entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8080 --log-level info

instance_class: B1

basic_scaling:
  max_instances: 1
  idle_timeout: 1m
